spring:
  application:
    name: schedule
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

feign:
  business:
    url: ${BUSINESS_CHECK_URL}
    check:
      service-key: ${BUSINESS_CHECK_SERVICE_KEY}

---

firebase:
  project:
    id: ${FIREBASE_PROJECT_ID}
  key:
    path: ${FCM_KEY_PATH}

---

server:
  port: 9000

---

#oauth:
#  kakao:
#    iss: "https://kauth.kakao.com"
#    client-id: ${OAUTH_KAKAO_CLIENT_ID}