spring:
  application:
    name: schedule
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql
  data:
    redis:
      host: ${DATA_REDIS_HOST}
      port: ${DATA_REDIS_PORT}
  access-token:
    expired-date: ${ACCESS_TOKEN_EXPIRED_DATE}

---

oauth:
  kakao:
    iss: "https://kauth.kakao.com"
    client-id: ${OAUTH_KAKAO_CLIENT_ID} # Kakao Developers REST API Key

---

feign:
  business:
    url: ${BUSINESS_CHECK_URL}
    check:
      service-key: ${BUSINESS_CHECK_SERVICE_KEY}

---

firebase:
  api:
    url: ${FIREBASE_API_URL}
  key:
    path: ${FCM_KEY_PATH}

---

secret:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-expired-in: ${JWT_EXPIRED_IN}

---

server:
  port: 9000

---

#oauth:
#  kakao:
#    iss: "https://kauth.kakao.com"
#    client-id: ${OAUTH_KAKAO_CLIENT_ID}